# Generated by Django 3.2.7 on 2021-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
