# Generated by Django 3.2.7 on 2021-09-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
